procesarImagen: nearlyBlack.c main.c
	gcc -o procesarImagen nearlyBlack.c main.c -lm -g 
	@echo ".exe creado con exito"
	@echo "         7ZZZZZZZZZZZZZZZZ.  "
	@echo "      ...OZZZZZZZZZZZZZZZZ...........  "
	@echo "      ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ.  "
	@echo "      ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ.  "
	@echo "      8888888888IIIIIII888III~   "
	@echo "   ...888D888888IIIIIII888III?.......              ----------------------------------------------------------------------------------"
	@echo "   888IIIO888IIIIIIIIII888IIIIIIIIII.            -                                                                                   |"
	@echo "   888IIIO888IIIIIIIIII888IIIIIIIIII.           -     Para Ejecutarlo solo escribe en la cosola:                                     |"
	@echo "   888IIIO888888IIIIIIIIII888OIIIIIIIIII  ------  ./procesarImagen -c parametro1 -u parametro2 -n parametro3 -b es parametroOpcional |"
	@echo "   888IIIO888888IIIIIIIIII888OIIIIIIIIII  ------                                                                                     |"
	@echo "   888888IIIIIIIIIIIIII8888888888888.           -                                                                                    |"
	@echo "   888888IIIIIIIIIIIIII8888888888888.            -                                                 let's GO!                         |"
	@echo "         IIIIIIIIIIIIIIIIIIIIIIII.                -----------------------------------------------------------------------------------"
	@echo "         =IIIIIIIIIIIIIIIIIIIIIII.  "
	@echo "      ZZZZZZZyyyBZZZZZZZZZZ....... "
	@echo "      ZZZZZZZyyyBZZZZZZZZZZ. "
	@echo "   ,,,ZZZZZZZyyyBZZZZZZZZZyO?....,~=~  "
	@echo "   ZZZZZZZZZZyyyBZZZZZZZyyyZZZZZZZZZZ.  "
	@echo "...ZZZZZZZZZZyyyBZZZZZZZZyyZZZZZZZZZZ.... "
	@echo "ZZZZZZZZZZZZZyyyyyyyyyyyyyBZZZZZZZZZZZZZZ "
	@echo "ZZZZZZZZZZZZZyyyyyyyyyyyyyBZZZZZZZZZZZZZZ "
	@echo "IIIIIIZZZZyyyIIIyyyyyyyIIIyyyZZZZIIIIIII "
	@echo "IIIIIIZZZZyyyIIIyyyyyyyIIIyyyZZZZIIIIIII "
	@echo "IIIIIIIIIZyyyyyyyyyyyyyyyyyyyZIIIIIIIIII "
	@echo "IIIIIIIIIZyyyyyyyyyyyyyyyyyyyZIIIIIIIIII "
	@echo "IIIIIIyyyyyyyyyyyyyyyyyyyyyyyyyyyIIIIIII "
	@echo "IIIIIIyyyyyyyyyyyyyyyyyyyyyyyyyyyIIIIIII "
	@echo "      yyyyyyyyyy.      yyyyyyyyyy.  "
	@echo "      yyyyyyyyyy.      yyyyyyyyyy. "
	@echo "   8888888888....      ...8888888888. "
	@echo "   8888888888             8888888888.  "
	@echo "8888888888888             88888888888888 "
	@echo "8888888888888             88888888888888 "
	@echo "8888888888888             88888888888888 "